services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: config-server
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
